### ISSUE TITLE
Add links to databend releases

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/link#4]
Using vercel edge functions, we can call GitHub APIs to get the latest release.

**Comment by Xuanwo** [comment]
We need to figure out how to provide this API.

- Via path?
- via query?
- Do we need to support version selection?
- Will we have `latest` and `stable`?
- Do we need to support countries (like `cn` and `us`) to make CDN works?

**Comment by Xuanwo** [comment]
Invite @PsiACE for discussion.

**Comment by PsiACE** [comment]
>     * Via path or via query?

both? `link.databend.rs/release/latest` and `link.databend.rs/release/nightly?version=v7.0.0-nightly`?

>     * Do we need to support version selection?

make sense

>     * Will we have `latest` and `stable`?

Now, we don't have any stable releases. So maybe we can use the `nightly`.

>     * Do we need to support countries (like `cn` and `us`) to make CDN works?

I would like to support at least `cn`, but if we use s3, can we not consider CDN.

**Comment by Xuanwo** [comment]
> I would like to support at least `cn`, but if we use s3, can we not consider CDN.

We can return cos links for cn and s3 links for us.

**Comment by Xuanwo** [comment]
Let's close this for now.
